name: Pytest

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6  # Replace with your desired Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run pytest
      run: pytest --cov --cov-report=html
      env:
        CI: true

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: ./htmlcov
